# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Load the shell dotfiles
# .extra can be used for other settings you don't want to commit
for file in ~/.dotfiles/{aliases,functions,commands,extra}; do
	[ -r "$file" ] && [ -f "$file" ] && source "$file";
done;
unset file;

# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="robbyrussell"

# Display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Oh-my-zsh Plugins
plugins=(git aliases)

source $ZSH/oh-my-zsh.sh
