#! /usr/bin/env bash

dirname="$(dirname "$0")"

function copyDotfilesDir() {
  echo "*** Copying Dotfiles to home"
	# rsync --exclude ".git/" \
	# 	--exclude ".DS_Store" \
	# 	-avh --no-perms dotfiles/ ~/.dotfiles;
}

function setupSimLinks() {
  echo "*** Setting up SymLinks"
  # ln -s $HOME/.dotfiles/zshrc $HOME/.zshrc || echo ".zshrc exists"
  # ln -s $HOME/.dotfiles/gitconfig $HOME/.gitconfig || echo ".gitconfig exists"
}

# Check for Homebrew and install if we don't have it
function setupHomebrew() {
  if ! command -v brew >/dev/null; then
    echo "*** Installing Xcode Command Line Tools..."
    # xcode-select --install
    echo "*** Installing Homebrew..."
    # /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  else
    echo "*** Homebrew already installed."
    echo "*** Updating brew"
    # brew update
  fi
}

# Install Xcode themes
function installXcodeThemes() {
  # source XcodeThemes/install.sh
}

function start() {
  copyDotfilesDir;
  setupSimLinks;
  setupHomebrew;
  
  ## oh-my-zsh
  echo "*** Installing Oh-my-zsh"
  # sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

  # echo "*** Please make sure to sign into the Mac App Store manually first."
  echo "*** Install Homebrew dependencies"
  # brew bundle

  installXcodeThemes;

  # source Scripts/macos-prefs

  echo "Finished."
}

echo "*** Setting up your Computer..."

echo "*** Pullling latest version of the repo"
# git pull origin main

# Initial prompt
if [ "$1" == "--force" -o "$1" == "-f" ]; then
	start;
else
	read -p "This may overwrite existing files in your home directory. Are you sure? (y/n) " -n 1
	echo ""
	if [[ $REPLY =~ ^[Yy]$ ]]; then
		start;
	fi
fi

