#!/usr/bin/env bash
source ./Utilities/print-color

printMessage "*** Installing Xcode Themes"
DESTDIR=~/Library/Developer/Xcode/UserData/FontAndColorThemes/
mkdir -p $DESTDIR
find . -name "*.xccolortheme" -exec cp '{}' $DESTDIR \;
