#!/usr/bin/env bash
source ./Utilities/print-color

printMessage "*** Setting up macOS Preferences"

# Close any open System Preferences panes, to prevent them from overriding
# settings we’re about to change
osascript -e 'tell application "System Preferences" to quit'

# Automatically hide and show the Dock
defaults write com.apple.dock autohide -bool true

# Enable the Develop menu and the Web Inspector in Safari
defaults write com.apple.Safari IncludeDevelopMenu -bool true
defaults write com.apple.Safari WebKitDeveloperExtrasEnabledPreferenceKey -bool true
defaults write com.apple.Safari com.apple.Safari.ContentPageGroupIdentifier.WebKit2DeveloperExtrasEnabled -bool true

# Don’t display the annoying prompt when quitting iTerm2
defaults write com.googlecode.iterm2 PromptOnQuit -bool false

# Trackpad: enable tap to click for this user and for the login screen
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true
defaults -currentHost write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
defaults write NSGlobalDomain com.apple.mouse.tapBehavior -int 1

###############################################################################
# Kill affected applications                                                  #
###############################################################################

for app in "Dock" \
  "Safari" \
	"Finder" \
	"SystemUIServer"; do
	killall "${app}" &> /dev/null
done
printMessage "*** Done. Note that some of these changes require a logout/restart to take effect."
