# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="robbyrussell"

# Display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Oh-my-zsh Plugins
plugins=(git aliases)

source $ZSH/oh-my-zsh.sh

# User configuration
alias grs1="git reset --soft HEAD~1"
alias issuu="cd ~/Repos/frontend-ios-app"
alias isu="cd ~/Repos/frontend-ios-app"
alias recap="cd ~/Repos/Recap/"
alias aliases="acs"
