#!/usr/bin/env bash
source ./Scripts/Utilities/print-color

# Close any open System Settings panes, to prevent them from overriding
# settings we’re about to change
# Preferences -> Settings for macOS Ventura
osascript -e 'tell application "System Settings" to quit'

# https://tonsky.me/blog/monitors/
# Disabling subpixel font smoothing
defaults -currentHost write -g AppleFontSmoothing -int 0

# Automatically hide and show the Dock
defaults write com.apple.dock autohide -bool true

# Enable automatic software update checks
defaults write com.apple.SoftwareUpdate AutomaticCheckEnabled -bool true

# Download newly available updates in background
defaults write com.apple.SoftwareUpdate AutomaticDownload -bool true

# Enable the Develop menu in Safari
open -ja safari # Open safari at least once before configuring defaults.
defaults write com.apple.Safari.SandboxBroker ShowDevelopMenu -bool true

# Trackpad: enable tap to click for this user and for the login screen
defaults write com.apple.AppleMultitouchTrackpad Clicking -bool true
defaults write com.apple.driver.AppleBluetoothMultitouch.trackpad Clicking -bool true
defaults -currentHost write NSGlobalDomain com.apple.mouse.tapBehavior -int 1
defaults write NSGlobalDomain com.apple.mouse.tapBehavior -int 1

###############################################################################
# Kill affected applications                                                  #
###############################################################################

for app in "Dock" \
	"Safari" \
	"Finder" \
	"SystemUIServer"; do
	killall "${app}" &> /dev/null
done
printMessage "*** Done. Note that some of these changes require a logout/restart to take effect."
